<h1 align="center">
 <b>PROYECTO INDIVIDUAL Nº2</b>
</h1>

# <h1 align="center">**`Siniestros viales`**</h1>
<h1 align="center" style="color: yellow;">Londero Walter Oscar</h1>

<p align="center">
<img src = "https://static.lajornadaestadodemexico.com/wp-content/uploads/2022/08/Siniestros-viales.jpg" height = 500>
<p>

# Proyecto Individual Nº2 - Siniestros Viales

## **Descripción del Problema**

Los siniestros viales son eventos que involucran vehículos en las vías públicas y pueden tener graves consecuencias. En Buenos Aires, estos incidentes son una preocupación debido al alto volumen de tráfico y densidad poblacional. Reducir las tasas de mortalidad por siniestros viales es crucial para mejorar la seguridad vial. En Argentina, los siniestros viales causan alrededor de 4.000 muertes al año, siendo una de las principales causas de muertes violentas. El Observatorio de Movilidad y Seguridad Vial solicita un proyecto de análisis de datos para ayudar a reducir las víctimas fatales de siniestros viales en Buenos Aires, proporcionando un dataset sobre homicidios en siniestros viales ocurridos entre 2016-2021.

El dataset se encuentra en: https://data.buenosaires.gob.ar/dataset/victimas-siniestros-viales

### Contexto

En Argentina, los siniestros viales causan un alto número de muertes cada año, superando incluso a otras causas de muerte violenta. El Observatorio de Movilidad y Seguridad Vial de Buenos Aires busca reducir estas cifras proporcionando información para tomar medidas efectivas.

### Rol a Desarrollar

El proyecto implica el análisis de datos sobre homicidios en siniestros viales en Buenos Aires entre 2016 y 2021. El objetivo es proporcionar información que permita a las autoridades locales tomar medidas para reducir la cantidad de víctimas fatales.


# <span style="color: #FF9843">**ETL**</span>

## <span style="color: #FFDD95">**Extracción**</span>

_Estas son las Librerias necesarias para la ejecución del Proyecto:_

In [9]:
!pip freeze > requirements.txt

In [10]:
with open('requirements.txt', 'r') as archivo:
    contenido = archivo.read()
    print(contenido)

aiohttp==3.9.5
aiosignal==1.3.1
annotated-types==0.6.0
anyio==4.3.0
asttokens==2.4.1
attrs==23.2.0
beautifulsoup4==4.12.3
branca==0.7.2
cachetools==5.3.3
certifi==2024.2.2
charset-normalizer==3.3.2
click==8.1.7
click-plugins==1.1.1
cligj==0.7.2
colorama==0.4.6
comm==0.2.2
contourpy==1.2.1
cycler==0.12.1
datasketch==1.6.4
datasketches==5.0.2
debugpy==1.8.1
decorator==5.1.1
dfsummary==0.4
dnspython==2.6.1
email_validator==2.1.1
et-xmlfile==1.1.0
executing==2.0.1
fastapi==0.111.0
fastapi-cli==0.0.3
filelock==3.14.0
fiona==1.9.6
folium==0.16.0
fonttools==4.51.0
frozenlist==1.4.1
functions==0.7.0
gdown==5.2.0
geojson==3.1.0
geopandas==0.14.4
google-auth==2.29.0
google-auth-oauthlib==1.2.0
greenlet==3.0.3
gspread==6.1.0
h11==0.14.0
httpcore==1.0.5
httplib2==0.22.0
httptools==0.6.1
httpx==0.27.0
idna==3.7
ipykernel==6.29.4
ipython==8.24.0
jedi==0.19.1
Jinja2==3.1.4
joblib==1.4.2
jupyter_client==8.6.1
jupyter_core==5.7.2
kiwisolver==1.4.5
lambdaprompt==0.6.1
markdown-it-py==3.0.0
MarkupSafe==2

In [11]:
import pandas as pd
import numpy as np
from summarytools import dfSummary
import requests


In [12]:
# URL de exportación de Google Sheets
url = 'https://docs.google.com/spreadsheets/d/1nq00jGIZHQ1RLSET43zKnUsMsoFb-pBg/export?format=xlsx'

# Nombre del archivo donde se guardará la descarga
filename = 'spreadsheet.xlsx'

# Hacer la solicitud GET a la URL
response = requests.get(url)

# Guardar el contenido de la respuesta en un archivo
with open(filename, 'wb') as file:
    file.write(response.content)

print(f'El archivo se ha descargado y guardado como {filename}')

El archivo se ha descargado y guardado como spreadsheet.xlsx


## <span style="color: #FFDD95">**Transformación**</span>

### <span style="color: #8DECB4">**1-Explorar y Limpiar Datos**</span>

****
<span style="color: #FAEF5D">Carga de los datos:</span>

Se importa la información de cada hoja del archivo en un df diferente:

In [13]:
# Read the downloaded spreadsheet into DataFrames
df_hechos = pd.read_excel(filename, sheet_name='HECHOS')
df_victimas = pd.read_excel(filename, sheet_name='VICTIMAS')

Hacemos un primer análisis de la información:

In [14]:
# Print DataFrames
print("Datos de la hoja HECHOS:")
print(df_hechos)

Datos de la hoja HECHOS:
            ID  N_VICTIMAS      FECHA  AAAA  MM  DD      HORA  HH  \
0    2016-0001           1 2016-01-01  2016   1   1  04:00:00   4   
1    2016-0002           1 2016-01-02  2016   1   2  01:15:00   1   
2    2016-0003           1 2016-01-03  2016   1   3  07:00:00   7   
3    2016-0004           1 2016-01-10  2016   1  10  00:00:00   0   
4    2016-0005           1 2016-01-21  2016   1  21  05:20:00   5   
..         ...         ...        ...   ...  ..  ..       ...  ..   
691  2021-0093           1 2021-12-13  2021  12  13  17:10:00  17   
692  2021-0094           1 2021-12-20  2021  12  20  01:10:00   1   
693  2021-0095           1 2021-12-30  2021  12  30  00:43:00   0   
694  2021-0096           1 2021-12-15  2021  12  15  10:30:00  10   
695  2021-0097           1 2021-11-18  2021  11  18  06:10:00   6   

                               LUGAR_DEL_HECHO TIPO_DE_CALLE  ...  Altura  \
0    AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ       AVENIDA  ...    

In [15]:
print("\nDatos de la hoja VICTIMAS:")
print(df_victimas)


Datos de la hoja VICTIMAS:
      ID_hecho      FECHA  AAAA  MM  DD                   ROL VICTIMA  \
0    2016-0001 2016-01-01  2016   1   1             CONDUCTOR    MOTO   
1    2016-0002 2016-01-02  2016   1   2             CONDUCTOR    AUTO   
2    2016-0003 2016-01-03  2016   1   3             CONDUCTOR    MOTO   
3    2016-0004 2016-01-10  2016   1  10             CONDUCTOR    MOTO   
4    2016-0005 2016-01-21  2016   1  21             CONDUCTOR    MOTO   
..         ...        ...   ...  ..  ..                   ...     ...   
712  2021-0092 2021-12-12  2021  12  12                PEATON  PEATON   
713  2021-0093 2021-12-13  2021  12  13  PASAJERO_ACOMPAÑANTE    MOTO   
714  2021-0094 2021-12-20  2021  12  20  PASAJERO_ACOMPAÑANTE    MOTO   
715  2021-0095 2021-12-30  2021  12  30             CONDUCTOR    MOTO   
716  2021-0096 2021-12-15  2021  12  15             CONDUCTOR    AUTO   

          SEXO EDAD  FECHA_FALLECIMIENTO  
0    MASCULINO   19  2016-01-01 00:00:00  
1    MASC

Obtenemos la información general de los df y analizamos tipos de datos y futuras transformaciones:

In [16]:
# Obtener información general del DataFrame
df_hechos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 696 entries, 0 to 695
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   ID                     696 non-null    object        
 1   N_VICTIMAS             696 non-null    int64         
 2   FECHA                  696 non-null    datetime64[ns]
 3   AAAA                   696 non-null    int64         
 4   MM                     696 non-null    int64         
 5   DD                     696 non-null    int64         
 6   HORA                   696 non-null    object        
 7   HH                     696 non-null    object        
 8   LUGAR_DEL_HECHO        696 non-null    object        
 9   TIPO_DE_CALLE          696 non-null    object        
 10  Calle                  695 non-null    object        
 11  Altura                 129 non-null    float64       
 12  Cruce                  525 non-null    object        
 13  Direc

In [17]:
df_victimas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 717 entries, 0 to 716
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype         
---  ------               --------------  -----         
 0   ID_hecho             717 non-null    object        
 1   FECHA                717 non-null    datetime64[ns]
 2   AAAA                 717 non-null    int64         
 3   MM                   717 non-null    int64         
 4   DD                   717 non-null    int64         
 5   ROL                  717 non-null    object        
 6   VICTIMA              717 non-null    object        
 7   SEXO                 717 non-null    object        
 8   EDAD                 717 non-null    object        
 9   FECHA_FALLECIMIENTO  717 non-null    object        
dtypes: datetime64[ns](1), int64(3), object(6)
memory usage: 56.1+ KB


Como el reemplazante "SD" de datos nulos posee diferencias con respecto a mayúsculas y minúsculas debemos unificarlos:

In [18]:
df_hechos.isnull().sum()

ID                         0
N_VICTIMAS                 0
FECHA                      0
AAAA                       0
MM                         0
DD                         0
HORA                       0
HH                         0
LUGAR_DEL_HECHO            0
TIPO_DE_CALLE              0
Calle                      1
Altura                   567
Cruce                    171
Dirección Normalizada      8
COMUNA                     0
XY (CABA)                  0
pos x                      0
pos y                      0
PARTICIPANTES              0
VICTIMA                    0
ACUSADO                    0
dtype: int64

Los valores nulos son significativos en el df_hechos en dos columnas principalmente, Altura con 567 valores faltantes y Cruce con 171 faltantes. Se van a conservar las columnas pero se tendra en cuanta para analisis posteriores que puedan involucrar estas columnas.

Reemplazar los valores nulos en HORA y HH con 25, debido a que es un tipo numérico y facilmente reconocible posteriormente en el análisisya ya que no corresponde a una hora válida:

In [19]:
# Reemplazar los valores nulos en las columnas 'HORA' y 'HH' con 0
df_hechos['HORA'] = df_hechos['HORA'].fillna('25:00')
df_hechos['HH'] = df_hechos['HH'].fillna(25)

Reemplazar los valores nulos en LUGAR_DEL_HECHO, Calle, Altura, Cruce, Direccion Normalizada, VICTIMA, y ACUSADO con 'SD'.


In [20]:
# Reemplazar los valores nulos en las columnas especificadas con 'SD'
columns_to_replace_with_sd = ['LUGAR_DEL_HECHO', 'Calle', 'Altura', 'Cruce', 'Dirección Normalizada', 'VICTIMA', 'ACUSADO']
df_hechos[columns_to_replace_with_sd] = df_hechos[columns_to_replace_with_sd].fillna('SD')

In [21]:
df_victimas.isnull().sum()

ID_hecho               0
FECHA                  0
AAAA                   0
MM                     0
DD                     0
ROL                    0
VICTIMA                0
SEXO                   0
EDAD                   0
FECHA_FALLECIMIENTO    0
dtype: int64

El df_victimas no contiene datos nulos.

Análisis de columnas con valores NaN

In [22]:
df_hechos[["Calle", "Altura", "Dirección Normalizada", "Cruce"]][:5]

Calle  Altura  \
0  PIEDRA BUENA AV.      SD   
1    PAZ, GRAL. AV.      SD   
2    ENTRE RIOS AV.  2034.0   
3    LARRAZABAL AV.      SD   
4      SAN JUAN AV.      SD   

                               Dirección Normalizada  \
0  PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...   
1               PAZ, GRAL. AV. y DE LOS CORRALES AV.   
2                                ENTRE RIOS AV. 2034   
3          LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.   
4            SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.   

                                 Cruce  
0  FERNANDEZ DE LA CRUZ, F., GRAL. AV.  
1                  DE LOS CORRALES AV.  
2                                   SD  
3             VILLEGAS, CONRADO, GRAL.  
4              SAENZ PE?A, LUIS, PRES.

Corroboramos si podemos extraer de la dirección normalizada los datos necesarios para completar la columna Altura y esta información no se encuentra en ningu otro lugar. Por lo que el análisis debe continuar sin estos datos.

In [23]:
# Definir las columnas a revisar
columns_to_check = ['Calle', 'Altura', 'Dirección Normalizada', 'Cruce']

# Contar la cantidad de valores 'SD' en cada columna
sd_counts = df_hechos[columns_to_check].apply(lambda x: (x == 'SD').sum())

# Mostrar los resultados
print(sd_counts)

Calle                      1
Altura                   567
Dirección Normalizada      8
Cruce                    171
dtype: int64


La columna **`Altura`** posee gran cantidad de datos faltantes y con la informacion que se tine no hay forma de completarla. En este caso la cantidad de faltantes corresponde a más del 80% de los datos. En este caso debemos eliminarla:

In [24]:
# Se elimina la columna "Altura"
df_hechos= df_hechos.drop("Altura", axis=1)
df_hechos.columns

Index(['ID', 'N_VICTIMAS', 'FECHA', 'AAAA', 'MM', 'DD', 'HORA', 'HH',
       'LUGAR_DEL_HECHO', 'TIPO_DE_CALLE', 'Calle', 'Cruce',
       'Dirección Normalizada', 'COMUNA', 'XY (CABA)', 'pos x', 'pos y',
       'PARTICIPANTES', 'VICTIMA', 'ACUSADO'],
      dtype='object')

Ahora podemos ver si hay información duplicada en nuestro df:

In [25]:
df_hechos.duplicated().sum()

0

In [26]:
df_victimas.duplicated().sum()

0

En los dataframes no hubo entradas repetidas y el shape de los archivos sigue el mismo:

In [27]:
num_rows = df_hechos.shape[0]
print("Número de filas en df_hechos:", num_rows)

Número de filas en df_hechos: 696


In [28]:
num_rows = df_victimas.shape[0]
print("Número de filas en df_victimas:", num_rows)

Número de filas en df_victimas: 717


Corroboramos la info de elementos nulos en df_victimas:

In [29]:
df_victimas

ID_hecho      FECHA  AAAA  MM  DD                   ROL VICTIMA  \
0    2016-0001 2016-01-01  2016   1   1             CONDUCTOR    MOTO   
1    2016-0002 2016-01-02  2016   1   2             CONDUCTOR    AUTO   
2    2016-0003 2016-01-03  2016   1   3             CONDUCTOR    MOTO   
3    2016-0004 2016-01-10  2016   1  10             CONDUCTOR    MOTO   
4    2016-0005 2016-01-21  2016   1  21             CONDUCTOR    MOTO   
..         ...        ...   ...  ..  ..                   ...     ...   
712  2021-0092 2021-12-12  2021  12  12                PEATON  PEATON   
713  2021-0093 2021-12-13  2021  12  13  PASAJERO_ACOMPAÑANTE    MOTO   
714  2021-0094 2021-12-20  2021  12  20  PASAJERO_ACOMPAÑANTE    MOTO   
715  2021-0095 2021-12-30  2021  12  30             CONDUCTOR    MOTO   
716  2021-0096 2021-12-15  2021  12  15             CONDUCTOR    AUTO   

          SEXO EDAD  FECHA_FALLECIMIENTO  
0    MASCULINO   19  2016-01-01 00:00:00  
1    MASCULINO   70  2016-01-02 00:00:00  
2    MASCULINO   30  2016-01-03 00:00:00  
3    MASCULINO   18                   SD  
4    MASCULINO   29  2016-02-01 00:00:00  
..         ...  ...                  ...  
712   FEMENINO   50  2021-12-12 00:00:00  
713   FEMENINO   18  2021-12-18 00:00:00  
714   FEMENINO   43  2021-12-20 00:00:00  
715  MASCULINO   27  2022-01-02 00:00:00  
716  MASCULINO   60  2021-12-20 00:00:00  

[717 rows x 10 columns]

In [30]:
df_victimas.isnull().sum()

ID_hecho               0
FECHA                  0
AAAA                   0
MM                     0
DD                     0
ROL                    0
VICTIMA                0
SEXO                   0
EDAD                   0
FECHA_FALLECIMIENTO    0
dtype: int64

Renombrar la columna: Se usa el método rename con el parámetro inplace=True para cambiar el nombre de la columna ID_hecho a ID.

In [31]:
# Renombrar la columna ID_hecho a ID
df_victimas.rename(columns={'ID_hecho': 'ID'}, inplace=True)

    Esto será útil para hacer posteriormente el Join.

Verificamos que todo esta completo y no tenemos valores nulos en Nuestros DataFrames:

In [32]:
df_hechos.isnull().sum()

ID                       0
N_VICTIMAS               0
FECHA                    0
AAAA                     0
MM                       0
DD                       0
HORA                     0
HH                       0
LUGAR_DEL_HECHO          0
TIPO_DE_CALLE            0
Calle                    0
Cruce                    0
Dirección Normalizada    0
COMUNA                   0
XY (CABA)                0
pos x                    0
pos y                    0
PARTICIPANTES            0
VICTIMA                  0
ACUSADO                  0
dtype: int64

In [33]:
# Verificar el cambio
df_victimas.isnull().sum()

ID                     0
FECHA                  0
AAAA                   0
MM                     0
DD                     0
ROL                    0
VICTIMA                0
SEXO                   0
EDAD                   0
FECHA_FALLECIMIENTO    0
dtype: int64

### <span style="color: #8DECB4">**2-Explorar y Transformar Datos**</span>

****
<span style="color: #FAEF5D">Correccón de Mayusculas y Minusculas:</span>

En este apartado se ha realizado la transformación de manera correcta sin ningún inconveniente, la unificación de la información a mayúsculas ayuda a la prolijidad y a evitar errores de escritura en formulas o funciones, evitando así chequear en todo momento el nombre de columnas para no escribir mal.

In [34]:
def convertir_columnas(df):
  """
  Convierte los nombres de las columnas de un DataFrame a mayúsculas y elimina los espacios.

  Parámetros:
    df: El DataFrame al que se le aplicarán las modificaciones.

  Retorno:
    Un DataFrame con los nombres de las columnas modificados.
  """
  df.columns = df.columns.str.upper().str.replace(" ", "_")
  return df

# Aplicamos la función a cada DataFrame
df_hechos = convertir_columnas(df_hechos)
df_victimas = convertir_columnas(df_victimas)

Hacemos una presentacón de como esta presentada la informacion en nuestros DataFrames:

In [35]:
df_hechos.head(2)

ID  N_VICTIMAS      FECHA  AAAA  MM  DD      HORA HH  \
0  2016-0001           1 2016-01-01  2016   1   1  04:00:00  4   
1  2016-0002           1 2016-01-02  2016   1   2  01:15:00  1   

                             LUGAR_DEL_HECHO TIPO_DE_CALLE             CALLE  \
0  AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ       AVENIDA  PIEDRA BUENA AV.   
1          AV GRAL PAZ  Y AV DE LOS CORRALES      GRAL PAZ    PAZ, GRAL. AV.   

                                 CRUCE  \
0  FERNANDEZ DE LA CRUZ, F., GRAL. AV.   
1                  DE LOS CORRALES AV.   

                               DIRECCIÓN_NORMALIZADA  COMUNA  \
0  PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...       8   
1               PAZ, GRAL. AV. y DE LOS CORRALES AV.       9   

                               XY_(CABA)         POS_X         POS_Y  \
0  Point (98896.78238426 93532.43437792)  -58.47533969  -34.68757022   
1  Point (95832.05571093 95505.41641999)  -58.50877521  -34.66977709   

    PARTICIPANTES VICTIMA    ACUSADO  
0       MOTO-AUTO    MOTO       AUTO  
1  AUTO-PASAJEROS    AUTO  PASAJEROS

In [36]:
df_victimas.head(2)

ID      FECHA  AAAA  MM  DD        ROL VICTIMA       SEXO EDAD  \
0  2016-0001 2016-01-01  2016   1   1  CONDUCTOR    MOTO  MASCULINO   19   
1  2016-0002 2016-01-02  2016   1   2  CONDUCTOR    AUTO  MASCULINO   70   

   FECHA_FALLECIMIENTO  
0  2016-01-01 00:00:00  
1  2016-01-02 00:00:00

In [37]:
dfSummary(df_hechos)

In [38]:
dfSummary(df_victimas)

### <span style="color: #8DECB4">**3-Unificar DataSet**</span>

Los datasets comparten información repetida por lo que debemos eliminar en alguno de ellos estas columnas que se repetirán en el df final:

In [39]:
# Se eliminan las columnas repetidas
df_victimas = df_victimas.drop(['FECHA', 'AAAA', 'MM', 'DD', 'VICTIMA'], axis=1)
df_victimas.columns

Index(['ID', 'ROL', 'SEXO', 'EDAD', 'FECHA_FALLECIMIENTO'], dtype='object')

In [40]:
df_victimas

ID                   ROL       SEXO EDAD  FECHA_FALLECIMIENTO
0    2016-0001             CONDUCTOR  MASCULINO   19  2016-01-01 00:00:00
1    2016-0002             CONDUCTOR  MASCULINO   70  2016-01-02 00:00:00
2    2016-0003             CONDUCTOR  MASCULINO   30  2016-01-03 00:00:00
3    2016-0004             CONDUCTOR  MASCULINO   18                   SD
4    2016-0005             CONDUCTOR  MASCULINO   29  2016-02-01 00:00:00
..         ...                   ...        ...  ...                  ...
712  2021-0092                PEATON   FEMENINO   50  2021-12-12 00:00:00
713  2021-0093  PASAJERO_ACOMPAÑANTE   FEMENINO   18  2021-12-18 00:00:00
714  2021-0094  PASAJERO_ACOMPAÑANTE   FEMENINO   43  2021-12-20 00:00:00
715  2021-0095             CONDUCTOR  MASCULINO   27  2022-01-02 00:00:00
716  2021-0096             CONDUCTOR  MASCULINO   60  2021-12-20 00:00:00

[717 rows x 5 columns]

In [41]:
df_hechos

ID  N_VICTIMAS      FECHA  AAAA  MM  DD      HORA  HH  \
0    2016-0001           1 2016-01-01  2016   1   1  04:00:00   4   
1    2016-0002           1 2016-01-02  2016   1   2  01:15:00   1   
2    2016-0003           1 2016-01-03  2016   1   3  07:00:00   7   
3    2016-0004           1 2016-01-10  2016   1  10  00:00:00   0   
4    2016-0005           1 2016-01-21  2016   1  21  05:20:00   5   
..         ...         ...        ...   ...  ..  ..       ...  ..   
691  2021-0093           1 2021-12-13  2021  12  13  17:10:00  17   
692  2021-0094           1 2021-12-20  2021  12  20  01:10:00   1   
693  2021-0095           1 2021-12-30  2021  12  30  00:43:00   0   
694  2021-0096           1 2021-12-15  2021  12  15  10:30:00  10   
695  2021-0097           1 2021-11-18  2021  11  18  06:10:00   6   

                               LUGAR_DEL_HECHO TIPO_DE_CALLE  \
0    AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ       AVENIDA   
1            AV GRAL PAZ  Y AV DE LOS CORRALES      GRAL PAZ   
2                           AV ENTRE RIOS 2034       AVENIDA   
3        AV LARRAZABAL Y GRAL VILLEGAS CONRADO       AVENIDA   
4    AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA        AVENIDA   
..                                         ...           ...   
691                          AV. RIESTRA Y MOM       AVENIDA   
692                    AU DELLEPIANE Y LACARRA     AUTOPISTA   
693                        AV. GAONA Y TERRADA       AVENIDA   
694                         AV. EVA PERON 4071       AVENIDA   
695                    PADRE CARLOS MUJICA 709         CALLE   

                            CALLE                                CRUCE  \
0                PIEDRA BUENA AV.  FERNANDEZ DE LA CRUZ, F., GRAL. AV.   
1                  PAZ, GRAL. AV.                  DE LOS CORRALES AV.   
2                  ENTRE RIOS AV.                                   SD   
3                  LARRAZABAL AV.             VILLEGAS, CONRADO, GRAL.   
4                    SAN JUAN AV.              SAENZ PE?A, LUIS, PRES.   
..                            ...                                  ...   
691                   RIESTRA AV.                                  MOM   
692  DELLEPIANE, LUIS, TTE. GRAL.                          LACARRA AV.   
693                     GAONA AV.                              TERRADA   
694                PERON, EVA AV.                                   SD   
695           PADRE CARLOS MUJICA                                   SD   

                                 DIRECCIÓN_NORMALIZADA  COMUNA  \
0    PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...       8   
1                 PAZ, GRAL. AV. y DE LOS CORRALES AV.       9   
2                                  ENTRE RIOS AV. 2034       1   
3            LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.       8   
4              SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.       1   
..                                                 ...     ...   
691                                  RIESTRA AV. y MOM       7   
692         DELLEPIANE, LUIS, TTE. GRAL. y LACARRA AV.       9   
693                                GAONA AV. y TERRADA      11   
694                                PERON, EVA AV. 4071       9   
695                            PADRE CARLOS MUGICA 709       1   

                                   XY_(CABA)         POS_X         POS_Y  \
0      Point (98896.78238426 93532.43437792)  -58.47533969  -34.68757022   
1      Point (95832.05571093 95505.41641999)  -58.50877521  -34.66977709   
2     Point (106684.29090040 99706.57687843)  -58.39040293  -34.63189362   
3      Point (99840.65224780 94269.16534422)  -58.46503904  -34.68092974   
4    Point (106980.32827929 100752.16915795)  -58.38718297  -34.62246630   
..                                       ...           ...           ...   
691   Point (102728.60090138 98186.24929177)  -58.43353773  -34.64561636   
692    Point (99624.29795829 97569.69801131)  -58.46739825  -34.65117757   
693   Point (99116.45492358 101045.23284826)  -5

In [43]:
len(df_hechos)

696

In [44]:
len(df_victimas)

717

Para fusionar los df se utiliza la función Merge.

In [ ]:
viales_clean = df_victimas.merge(df_hechos, on="ID", how="left")
viales_clean.columns

Index(['ID', 'ROL', 'SEXO', 'EDAD', 'FECHA_FALLECIMIENTO', 'N_VICTIMAS',
       'FECHA', 'AAAA', 'MM', 'DD', 'HORA', 'HH', 'LUGAR_DEL_HECHO',
       'TIPO_DE_CALLE', 'CALLE', 'CRUCE', 'DIRECCIÓN_NORMALIZADA', 'COMUNA',
       'XY_(CABA)', 'POS_X', 'POS_Y', 'PARTICIPANTES', 'VICTIMA', 'ACUSADO'],
      dtype='object')

In [ ]:
viales_clean

ID                   ROL       SEXO EDAD  FECHA_FALLECIMIENTO  \
0    2016-0001             CONDUCTOR  MASCULINO   19  2016-01-01 00:00:00   
1    2016-0002             CONDUCTOR  MASCULINO   70  2016-01-02 00:00:00   
2    2016-0003             CONDUCTOR  MASCULINO   30  2016-01-03 00:00:00   
3    2016-0004             CONDUCTOR  MASCULINO   18                   SD   
4    2016-0005             CONDUCTOR  MASCULINO   29  2016-02-01 00:00:00   
..         ...                   ...        ...  ...                  ...   
712  2021-0092                PEATON   FEMENINO   50  2021-12-12 00:00:00   
713  2021-0093  PASAJERO_ACOMPAÑANTE   FEMENINO   18  2021-12-18 00:00:00   
714  2021-0094  PASAJERO_ACOMPAÑANTE   FEMENINO   43  2021-12-20 00:00:00   
715  2021-0095             CONDUCTOR  MASCULINO   27  2022-01-02 00:00:00   
716  2021-0096             CONDUCTOR  MASCULINO   60  2021-12-20 00:00:00   

     N_VICTIMAS      FECHA  AAAA  MM  DD  ...                         CALLE  \
0             1 2016-01-01  2016   1   1  ...              PIEDRA BUENA AV.   
1             1 2016-01-02  2016   1   2  ...                PAZ, GRAL. AV.   
2             1 2016-01-03  2016   1   3  ...                ENTRE RIOS AV.   
3             1 2016-01-10  2016   1  10  ...                LARRAZABAL AV.   
4             1 2016-01-21  2016   1  21  ...                  SAN JUAN AV.   
..          ...        ...   ...  ..  ..  ...                           ...   
712           1 2021-12-12  2021  12  12  ...                 RIVADAVIA AV.   
713           1 2021-12-13  2021  12  13  ...                   RIESTRA AV.   
714           1 2021-12-20  2021  12  20  ...  DELLEPIANE, LUIS, TTE. GRAL.   
715           1 2021-12-30  2021  12  30  ...                     GAONA AV.   
716           1 2021-12-15  2021  12  15  ...                PERON, EVA AV.   

                                   CRUCE  \
0    FERNANDEZ DE LA CRUZ, F., GRAL. AV.   
1                    DE LOS CORRALES AV.   
2                                     SD   
3               VILLEGAS, CONRADO, GRAL.   
4                SAENZ PE?A, LUIS, PRES.   
..                                   ...   
712                       PUEYRREDON AV.   
713                                  MOM   
714                          LACARRA AV.   
715                              TERRADA   
716                                   SD   

                                 DIRECCIÓN_NORMALIZADA COMUNA  \
0    PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...      8   
1                 PAZ, GRAL. AV. y DE LOS CORRALES AV.      9   
2                                  ENTRE RIOS AV. 2034      1   
3            LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.      8   
4              SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.      1   
..                                                 ...    ...   
712                     RIVADAVIA AV. y PUEYRREDON AV.      3   
713                                  RIESTRA AV. y MOM      7   
714         DELLEPIANE, LUIS, TTE. GRAL. y LACARRA AV.      9   
715                                GAONA AV. y TERRADA     11   
716                                PERON, EVA AV. 4071      9   

                                   XY_(CABA)         POS_X         POS_Y  \
0      Point (98896.78238426 93532.43437792)  -58.47533969  -34.68757022   
1      Point (95832.05571093 95505.41641999)  -58.50877521  -34.66977709   
2     Point (106684.29090040 99706.57687843)  -58.39040293  -34.63189362   
3      Point (99840.65224780 94269.16534422)  -58.46503904  -34.68092974   
4    Point (106980.32827929 100752.16915795)  -58.38718297  -34.62246630   
..                                       ...           ...           ...   
712  Point (105258.35368554 102122.93231400)  -58.40596860  -34.61011987   
713   Point (102728.60090138 98186.24929177)  -58.43353773  -34.64561636   
714    Point (99624.29795829 97569.69801131)  -58.46739825  -34.65117757   
715   Point (99116.45492358 101045.23284826)  -58.47293407  -34.6198

## <span style="color: #FFDD95">**Carga**</span>

In [ ]:
# Archivos DataFrame a exportar
viales_clean.to_csv('viales_clean.csv', index=False)